- id: protected-branch
  name: Protected branch
  description: Protect branches from committing without a dialogue
  entry: pre-commit-protected-branch
  language: python
  pass_filenames: false
  always_run: true